#!/usr/bin/env ruby
# encoding: utf-8
# frozen_string_literal: true

require 'optparse'

require 'chatrix'
require 'chatrix/bot'

require 'pp'

defaults = {
  config: Chatrix::Bot::Config::DEFAULT_CONFIG_PATH
}

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: chatrix-bot [options]'

  opts.on(
    '-g',
    '--generate [FILE]',
    'Generate config to specified file and exit.',
    "  FILE defaults to '#{defaults[:config]}'"
  ) do |file|
    file ||= defaults[:config]
    data = Chatrix::Bot::Config::DEFAULTS
    Chatrix::Bot::Config.new(file, data).save
    exit
  end

  opts.on(
    '-c',
    '--config FILE',
    'Specify the config file to use',
    "  (uses '#{defaults[:config]}' if not specified)"
  ) do |c|
    options[:config] = c
  end

  opts.on_tail('-v', '--version', 'Print version and exit') do
    puts "chatrix-bot v#{Chatrix::Bot::VERSION}, chatrix v#{Chatrix::VERSION}"
    exit
  end

  opts.on_tail('-h', '--help', 'Shows this help message and exits') do
    puts opts
    exit
  end
end.parse!

pp options
